<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Marker;

class MarkerDSeeder extends Seeder
{
    public function run(): void
    {
        $markers = [
                [
                    'shape_type' => 'Marker',
                    'status' => 'yellow',
                    'title' => 'Taman Nasional Komodo',
                    'location_name' => 'Manggarai Barat, NTT',
                    'description' => 'Habitat asli satwa endemik Komodo. Peningkatan jumlah wisatawan membawa dampak pada pengelolaan sampah dan perilaku satwa, sehingga aturan kunjungan mulai diperketat.',
                    'coordinates' => [-8.536, 119.480],
                    'latitude' => -8.536,
                    'longitude' => 119.480,
                    'eco_health_score' => 6.5,
                    'total_reports' => 1240,
                    'kebersihan' => '3/5',
                    'akses' => 'Menengah',
                    'populasi' => 'Sedang',
                    'category' => 'Perlu Perhatian',
                    'eco_rules' => [
                        ['text' => 'Patuhi jalur trekking yang disediakan.', 'type' => 'allowed'],
                        ['text' => 'Dilarang memberi makan satwa liar!', 'type' => 'warning'],
                        ['text' => 'Bawa kembali sampah plastik Anda.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'green',
                    'title' => 'Candi Borobudur',
                    'location_name' => 'Magelang, Jawa Tengah',
                    'description' => 'Situs warisan dunia UNESCO. Pengelolaan sangat baik dengan pembatasan jumlah pengunjung yang boleh naik ke area stupa untuk menjaga kelestarian batu candi.',
                    'coordinates' => [-7.607, 110.203],
                    'latitude' => -7.607,
                    'longitude' => 110.203,
                    'eco_health_score' => 8.9,
                    'total_reports' => 3100,
                    'kebersihan' => '5/5',
                    'akses' => 'Sangat Mudah',
                    'populasi' => 'Terpadu',
                    'category' => 'Terjaga',
                    'eco_rules' => [
                        ['text' => 'Gunakan sandal khusus (upanat) jika naik ke candi.', 'type' => 'allowed'],
                        ['text' => 'Jangan menyentuh relief batu.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'red',
                    'title' => 'Gunung Rinjani',
                    'location_name' => 'Lombok, NTB',
                    'description' => 'Gunung berapi dengan pemandangan Danau Segara Anak yang memukau. Sedang mengalami masalah kritis terkait tumpukan sampah pendaki di area kemah dan jalur pendakian.',
                    'coordinates' => [-8.411, 116.457],
                    'latitude' => -8.411,
                    'longitude' => 116.457,
                    'eco_health_score' => 3.2,
                    'total_reports' => 2150,
                    'kebersihan' => '1/5',
                    'akses' => 'Sulit',
                    'populasi' => 'Tinggi (Musiman)',
                    'category' => 'Kritis',
                    'eco_rules' => [
                        ['text' => 'Wajib mendaftar dan lapor barang bawaan.', 'type' => 'allowed'],
                        ['text' => 'Bawa turun semua sampah Anda, tanpa terkecuali!', 'type' => 'warning'],
                        ['text' => 'Dilarang membuang limbah sabun ke sumber air.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'green',
                    'title' => 'Raja Ampat',
                    'location_name' => 'Papua Barat Daya',
                    'description' => 'Surga bawah laut dengan keanekaragaman hayati laut tertinggi di dunia. Kesadaran konservasi sangat tinggi dengan sistem tarif lingkungan hidup untuk turis.',
                    'coordinates' => [-0.233, 130.516],
                    'latitude' => -0.233,
                    'longitude' => 130.516,
                    'eco_health_score' => 9.2,
                    'total_reports' => 890,
                    'kebersihan' => '5/5',
                    'akses' => 'Sulit',
                    'populasi' => 'Rendah',
                    'category' => 'Aman',
                    'eco_rules' => [
                        ['text' => 'Wajib bayar PIN (Tarif Layanan Lingkungan).', 'type' => 'allowed'],
                        ['text' => 'Dilarang menggunakan sarung tangan saat menyelam.', 'type' => 'warning'],
                        ['text' => 'Dilarang menyentuh terumbu karang.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'yellow',
                    'title' => 'Danau Toba',
                    'location_name' => 'Sumatera Utara',
                    'description' => 'Danau vulkanik terbesar di dunia. Mengalami tantangan ekologi berupa keramba jaring apung berlebih yang mempengaruhi kualitas air dan sanitasi wisata sekitar.',
                    'coordinates' => [2.616, 98.775],
                    'latitude' => 2.616,
                    'longitude' => 98.775,
                    'eco_health_score' => 5.4,
                    'total_reports' => 1670,
                    'kebersihan' => '3/5',
                    'akses' => 'Mudah',
                    'populasi' => 'Tinggi',
                    'category' => 'Perlu Perhatian',
                    'eco_rules' => [
                        ['text' => 'Dukung usaha pariwisata warga lokal.', 'type' => 'allowed'],
                        ['text' => 'Jangan membuang sampah sembarangan ke danau.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'green',
                    'title' => 'Taman Nasional Ujung Kulon',
                    'location_name' => 'Pandeglang, Banten',
                    'description' => 'Suaka alam perlindungan Badak Jawa bercula satu yang terancam punah. Lingkungan sangat terjaga karena pembatasan ketat untuk intervensi manusia.',
                    'coordinates' => [-6.744, 105.337],
                    'latitude' => -6.744,
                    'longitude' => 105.337,
                    'eco_health_score' => 9.5,
                    'total_reports' => 320,
                    'kebersihan' => '5/5',
                    'akses' => 'Menengah',
                    'populasi' => 'Sangat Rendah',
                    'category' => 'Terjaga',
                    'eco_rules' => [
                        ['text' => 'Ikuti instruksi pemandu wisata resmi.', 'type' => 'allowed'],
                        ['text' => 'Dilarang membuat kebisingan di area konservasi.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'yellow',
                    'title' => 'Gunung Bromo',
                    'location_name' => 'Probolinggo, Jawa Timur',
                    'description' => 'Destinasi ikonik dengan lautan pasir. Masalah utama adalah polusi udara dari ribuan jip wisata dan kerusakan savana akibat aktivitas yang tidak terkontrol.',
                    'coordinates' => [-7.942, 112.953],
                    'latitude' => -7.942,
                    'longitude' => 112.953,
                    'eco_health_score' => 5.1,
                    'total_reports' => 4500,
                    'kebersihan' => '3/5',
                    'akses' => 'Mudah',
                    'populasi' => 'Sangat Tinggi',
                    'category' => 'Waspada',
                    'eco_rules' => [
                        ['text' => 'Jaga kecepatan kendaraan di area pasir.', 'type' => 'allowed'],
                        ['text' => 'Dilarang merusak area savana teletubbies.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'red',
                    'title' => 'Kepulauan Seribu (Pulau Tertentu)',
                    'location_name' => 'DKI Jakarta',
                    'description' => 'Gugusan pulau di utara Jakarta. Beberapa pulau tak berpenghuni atau pulau wisata padat mengalami krisis penumpukan sampah kiriman dari teluk Jakarta dan limbah domestik.',
                    'coordinates' => [-5.584, 106.581],
                    'latitude' => -5.584,
                    'longitude' => 106.581,
                    'eco_health_score' => 2.8,
                    'total_reports' => 3800,
                    'kebersihan' => '1/5',
                    'akses' => 'Mudah',
                    'populasi' => 'Tinggi',
                    'category' => 'Kritis',
                    'eco_rules' => [
                        ['text' => 'Ikut serta dalam kegiatan beach clean-up.', 'type' => 'allowed'],
                        ['text' => 'Kurangi penggunaan air bersih yang terbatas.', 'type' => 'warning'],
                        ['text' => 'Dilarang membuang sampah ke laut!', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'yellow',
                    'title' => 'Nusa Penida',
                    'location_name' => 'Klungkung, Bali',
                    'description' => 'Pulau eksotis dengan tebing ikonik. Terkena dampak "overtourism" mendadak yang menyebabkan infrastruktur pengelolaan sampah kewalahan menangani limbah turis.',
                    'coordinates' => [-8.727, 115.544],
                    'latitude' => -8.727,
                    'longitude' => 115.544,
                    'eco_health_score' => 4.5,
                    'total_reports' => 2750,
                    'kebersihan' => '2/5',
                    'akses' => 'Menengah',
                    'populasi' => 'Tinggi',
                    'category' => 'Perlu Perhatian',
                    'eco_rules' => [
                        ['text' => 'Bawa botol minum (tumbler) sendiri.', 'type' => 'allowed'],
                        ['text' => 'Jangan buang puntung rokok sembarangan di tebing.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'green',
                    'title' => 'Desa Adat Wae Rebo',
                    'location_name' => 'Manggarai, NTT',
                    'description' => 'Desa tradisional di atas awan dengan rumah kerucut khas. Sistem ekowisata berbasis komunitas berjalan sangat baik, menjaga keseimbangan alam dan budaya.',
                    'coordinates' => [-8.769, 120.282],
                    'latitude' => -8.769,
                    'longitude' => 120.282,
                    'eco_health_score' => 8.8,
                    'total_reports' => 410,
                    'kebersihan' => '4/5',
                    'akses' => 'Sulit',
                    'populasi' => 'Rendah',
                    'category' => 'Terjaga',
                    'eco_rules' => [
                        ['text' => 'Patuhi adat istiadat warga setempat.', 'type' => 'allowed'],
                        ['text' => 'Konsumsi hasil bumi lokal dari desa.', 'type' => 'allowed'],
                        ['text' => 'Dilarang membawa makanan berbungkus plastik ke area desa.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'green',
                    'title' => 'Kawah Putih',
                    'location_name' => 'Bandung, Jawa Barat',
                    'description' => 'Kawah vulkanik dengan danau berwarna putih kehijauan. Pengelolaan area wisata oleh perhutani cukup bersih dan terorganisir dengan area hijau yang dipertahankan.',
                    'coordinates' => [-7.166, 107.402],
                    'latitude' => -7.166,
                    'longitude' => 107.402,
                    'eco_health_score' => 7.5,
                    'total_reports' => 1100,
                    'kebersihan' => '4/5',
                    'akses' => 'Sangat Mudah',
                    'populasi' => 'Tinggi',
                    'category' => 'Aman',
                    'eco_rules' => [
                        ['text' => 'Gunakan masker karena bau belerang yang kuat.', 'type' => 'allowed'],
                        ['text' => 'Buang sampah di tong sampah terpilah yang disediakan.', 'type' => 'allowed'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'yellow',
                    'title' => 'Pantai Parangtritis',
                    'location_name' => 'Bantul, Yogyakarta',
                    'description' => 'Pantai populer di pesisir selatan Jawa. Kondisi kebersihan sering menurun drastis saat musim libur panjang karena kurangnya kedisiplinan pengunjung membawa sampah mereka.',
                    'coordinates' => [-8.025, 110.334],
                    'latitude' => -8.025,
                    'longitude' => 110.334,
                    'eco_health_score' => 5.2,
                    'total_reports' => 3400,
                    'kebersihan' => '3/5',
                    'akses' => 'Sangat Mudah',
                    'populasi' => 'Sangat Tinggi',
                    'category' => 'Waspada',
                    'eco_rules' => [
                        ['text' => 'Gunakan fasilitas toilet umum dengan bijak.', 'type' => 'allowed'],
                        ['text' => 'Jangan buang sampah bekas makanan ke arah laut.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'green',
                    'title' => 'Taman Nasional Tanjung Puting',
                    'location_name' => 'Kotawaringin Barat, Kalteng',
                    'description' => 'Pusat rehabilitasi Orangutan terbesar di dunia. Menerapkan ekowisata perahu klotok yang ramah lingkungan dan edukatif.',
                    'coordinates' => [-2.984, 111.964],
                    'latitude' => -2.984,
                    'longitude' => 111.964,
                    'eco_health_score' => 8.7,
                    'total_reports' => 560,
                    'kebersihan' => '5/5',
                    'akses' => 'Menengah',
                    'populasi' => 'Rendah',
                    'category' => 'Terjaga',
                    'eco_rules' => [
                        ['text' => 'Jaga jarak aman dari Orangutan liar.', 'type' => 'allowed'],
                        ['text' => 'Dilarang bersuara keras di area feeding station.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'yellow',
                    'title' => 'Taman Nasional Bunaken',
                    'location_name' => 'Manado, Sulawesi Utara',
                    'description' => 'Taman laut yang indah namun kerap menghadapi kiriman sampah plastik dari daratan kota Manado saat musim hujan yang mengancam ekosistem terumbu karang.',
                    'coordinates' => [1.624, 124.760],
                    'latitude' => 1.624,
                    'longitude' => 124.760,
                    'eco_health_score' => 6.0,
                    'total_reports' => 1450,
                    'kebersihan' => '3/5',
                    'akses' => 'Mudah',
                    'populasi' => 'Menengah',
                    'category' => 'Perlu Perhatian',
                    'eco_rules' => [
                        ['text' => 'Pastikan operator selam Anda berlisensi ramah lingkungan.', 'type' => 'allowed'],
                        ['text' => 'Dilarang membuang sauh jangkar di area terumbu karang.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'red',
                    'title' => 'Gunung Semeru (Ranu Kumbolo)',
                    'location_name' => 'Lumajang, Jawa Timur',
                    'description' => 'Danau ikonik di jalur pendakian Semeru. Sering masuk status merah akibat ulah pendaki nakal yang meninggalkan sampah dan merusak vegetasi di area kemah.',
                    'coordinates' => [-8.107, 112.922],
                    'latitude' => -8.107,
                    'longitude' => 112.922,
                    'eco_health_score' => 3.9,
                    'total_reports' => 1900,
                    'kebersihan' => '2/5',
                    'akses' => 'Sulit',
                    'populasi' => 'Tinggi (Musiman)',
                    'category' => 'Kritis',
                    'eco_rules' => [
                        ['text' => 'Gunakan area toilet basah yang disediakan, jangan di sembarang tempat.', 'type' => 'allowed'],
                        ['text' => 'DILARANG KERAS mencuci alat masak/mandi di dalam air danau.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'green',
                    'title' => 'Pulau Weh (Sabang)',
                    'location_name' => 'Sabang, Aceh',
                    'description' => 'Titik nol kilometer Indonesia. Kondisi terumbu karang sangat sehat dan masyarakat lokal menjaga kebersihan pantai secara kolektif dengan sanksi adat.',
                    'coordinates' => [5.820, 95.318],
                    'latitude' => 5.820,
                    'longitude' => 95.318,
                    'eco_health_score' => 8.4,
                    'total_reports' => 600,
                    'kebersihan' => '4/5',
                    'akses' => 'Menengah',
                    'populasi' => 'Menengah',
                    'category' => 'Terjaga',
                    'eco_rules' => [
                        ['text' => 'Hargai kearifan lokal dan syariat yang berlaku.', 'type' => 'allowed'],
                        ['text' => 'Gunakan botol isi ulang.', 'type' => 'allowed'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'yellow',
                    'title' => 'Pantai Losari',
                    'location_name' => 'Makassar, Sulawesi Selatan',
                    'description' => 'Ruang publik dan ikon kota Makassar. Perhatian ekstra pada manajemen sampah komersial dari para pedagang makanan dan sampah plastik laut.',
                    'coordinates' => [-5.143, 119.408],
                    'latitude' => -5.143,
                    'longitude' => 119.408,
                    'eco_health_score' => 4.8,
                    'total_reports' => 2200,
                    'kebersihan' => '2/5',
                    'akses' => 'Sangat Mudah',
                    'populasi' => 'Sangat Tinggi',
                    'category' => 'Waspada',
                    'eco_rules' => [
                        ['text' => 'Minimalkan pembelian makanan berbungkus styrofoam.', 'type' => 'allowed'],
                        ['text' => 'Buang sampah pada tempat pemilahan.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'yellow',
                    'title' => 'Kawah Ijen',
                    'location_name' => 'Banyuwangi, Jawa Timur',
                    'description' => 'Fenomena api biru yang langka dan aktivitas tambang belerang. Gas beracun dan minimnya fasilitas sanitasi pengunjung memicu degradasi lingkungan sekitar rute pendakian.',
                    'coordinates' => [-8.058, 114.242],
                    'latitude' => -8.058,
                    'longitude' => 114.242,
                    'eco_health_score' => 5.5,
                    'total_reports' => 1800,
                    'kebersihan' => '3/5',
                    'akses' => 'Menengah',
                    'populasi' => 'Tinggi',
                    'category' => 'Perlu Perhatian',
                    'eco_rules' => [
                        ['text' => 'Gunakan masker gas standar industri.', 'type' => 'allowed'],
                        ['text' => 'Dilarang membuang masker medis bekas di area kawah.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'green',
                    'title' => 'Pantai Ora',
                    'location_name' => 'Maluku Tengah, Maluku',
                    'description' => 'Destinasi "Maldives" ala Indonesia yang tersembunyi. Ekosistem koral bawah air sangat perawan dengan pembatasan jumlah resor yang diizinkan beroperasi.',
                    'coordinates' => [-2.937, 129.231],
                    'latitude' => -2.937,
                    'longitude' => 129.231,
                    'eco_health_score' => 9.0,
                    'total_reports' => 250,
                    'kebersihan' => '5/5',
                    'akses' => 'Sulit',
                    'populasi' => 'Sangat Rendah',
                    'category' => 'Aman',
                    'eco_rules' => [
                        ['text' => 'Gunakan sunscreen berbahan dasar mineral alam.', 'type' => 'allowed'],
                        ['text' => 'Dilarang mengambil pasir atau karang laut.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
                [
                    'shape_type' => 'Marker',
                    'status' => 'green',
                    'title' => 'Kepulauan Derawan',
                    'location_name' => 'Berau, Kalimantan Timur',
                    'description' => 'Habitat bagi penyu hijau laut dan ubur-ubur tanpa sengat. Masyarakat dan pengelola sangat menjaga area peneluran penyu dari gangguan.',
                    'coordinates' => [2.285, 118.244],
                    'latitude' => 2.285,
                    'longitude' => 118.244,
                    'eco_health_score' => 8.2,
                    'total_reports' => 850,
                    'kebersihan' => '4/5',
                    'akses' => 'Menengah',
                    'populasi' => 'Menengah',
                    'category' => 'Terjaga',
                    'eco_rules' => [
                        ['text' => 'Matikan flash kamera saat melihat penyu bertelur.', 'type' => 'warning'],
                        ['text' => 'Dilarang berenang memakai lotion/sunscreen di danau ubur-ubur Kakaban.', 'type' => 'warning'],
                    ],
                    'user_id' => 1,
                ],
        ];

        foreach ($markers as $data) {
            Marker::create($data);
        }
    }
}
